### PR TITLE
fix: allow cxx compiler to tolerate options after arguments

### LINKED ISSUE #125: FSUM3010 seen for ports that require a C++ compiler
Ports which need a C++ compiler can see errors with the format of the compile commands.

e.g. cmakeport fails with:
```
Error when bootstrapping CMake:
Cannot find a C++ compiler that supports both C++11 and the specified C++ flags.
Please specify one using environment variable CXX.
The C++ flags are "-+ -qascii -qnocsect -qenum=int -O3 -qNOASCII -qNOOPT".
They can be changed using the environment variable CXXFLAGS.
See cmake_bootstrap.log for compilers attempted.
```
and cmake_bootstrap.log has:
```
FSUM3010 Specify a file with the correct suffix (.C, .hh, .i, .c, .i, .s, .o, .x, .p, .I, or .a), or a corresponding data set name, instead of -o./cmake_bootstrap_16908380_test.
Test failed to compile
```

### PR DESCRIPTION
**Pull request by dougburns**
Fixes #125 

Adding  _CXX_CCMODE into common.inc to match  _C89_CCMODE.

This is enough to fix the issue I was seeing with the cmake build, but I wonder whether we should have  _CC_CCMODE set as well to be consistent?

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Looks good to me. If @perry-ca isnt on review please add

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Comment by perry-ca** [comment]
I'd say set _CC_CCMODE too.  Otherwise looks good,

Did you find where these are documented?  I can't find anything outside of external references or PMR text.

**Comment by dougburns** [comment]
@perry-ca 
Added _CC_CCMODE as well.
The variables are documented here: [Compiler invocation using host environment variables](https://www.ibm.com/docs/en/zos/2.4.0?topic=descriptions-c89-compiler-invocation-using-host-environment-variables) as prefix_CCMODE

**Review by perry-ca — APPROVED** [review]
LGTM

**Review by MikeFultonDev — APPROVED** [review]
Lgtm

**Pull request merged**
