### PR TITLE
zopen convention changes to script files + -e option to specify custom buildenv + -d option to specify deps search paths

### PR DESCRIPTION
**Pull request by IgorTodorovskiIBM**
* Add zopen prefix to scripts and removed `.sh` suffix
* Adds a zopen driver script that can be invoked as follows:
  * `zopen build` - calls `zopen-build`
  * `zopen download` - called `zopen-download`
* Adds -e option support sourcing the env file, formerly `setenv.sh`, but now defaults to search for `buildenv`
* Adds -d/depspath option to specify search paths for dependencies 
* Also includes a few fixes to `zopen-download` 

**Once approved and prior to merging, all port repos under ZOSOpenTools will be modified to use the new convention**

Unfortunately, `git` is unable to detect that build.sh is renamed to zopen-build, even when I use `git mv build.sh zopen-build`

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
looks good - will you open a PR for each other repo too for the setenv.sh changes under a similar 'zopen' branch?

**Comment by IgorTodorovskiIBM** [comment]
> looks good - will you open a PR for each other repo too for the setenv.sh changes under a similar 'zopen' branch?

Yep, I plan to do that as well before merging this in

**Review by jshimoda9323 — APPROVED** [review]
Yes, looks good!

**Comment by IgorTodorovskiIBM** [comment]
I've created a PR for each port that changes all occurances of:
*`build.sh` to `zopen build`
* `PORT_` to `ZOPEN_`
* setenv.sh to buildenv

Also, the last commit in this PR changes the path deps search path from $HOME/zot to $HOME/zopen

**Pull request merged**
